# Generated by Django 4.2.1 on 2023-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chatInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=20)),
                ("senderName", models.CharField(max_length=20)),
                ("userMessage", models.TextField(max_length=100)),
                ("senderMessage", models.TextField(max_length=100)),
            ],
        ),
    ]
