# Generated by Django 4.2.4 on 2023-11-03 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0002_addlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatinfo",
            name="senderMessage",
        ),
    ]
