# Generated by Django 4.2.4 on 2023-11-04 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0004_chatinfo_sendermessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatinfo",
            old_name="senderMessage",
            new_name="sender",
        ),
    ]
