# Generated by Django 4.2.4 on 2023-11-06 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0005_rename_sendermessage_chatinfo_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatinfo",
            name="sender",
        ),
    ]
